
GET http://localhost:3001/subscribers

###

GET http://localhost:3001/subscribers/611c9b24630a12775cfde68c

###

POST  http://localhost:3001/subscribers
Content-Type: application/json

{
    "name": "Will Harvey",
    "email": "harvey22@gmail.com",
    "city": "Edmonton"    
}


###

DELETE http://localhost:3001/subscribers/611f13e55efa82732822890f

###

PATCH   http://localhost:3001/subscribers/611c9b24630a12775cfde68c
Content-Type: application/json

{
    "name": "Son Moon",
    "email": "son.moon@hotmail.com"
}